name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore --ignore-failed-sources
    - name: Build
      run: dotnet build ThinkBase.Client.csproj --configuration Release --no-restore
    - name: Publish NuGet
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: ThinkBase.Client.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
    - name: Write info to news Item
      id: hello
      uses: thinkbase-ai/newsitem_action@v1.14
      with:
        apiKey: ${{secrets.DARL_API_KEY}}
     
